spring:
  application:
    name: forkd-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/forkd_db
    username: postgres
    password: 123Jyo
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect